import type { Metadata } from "next";
import Link from "next/link";
import { BreadcrumbJsonLd } from "@/components/json-ld";
import {
  SectionHeading,
  Paragraph,
  Breadcrumb,
  PageTitle,
  ProseContainer,
  ContentCard,
} from "@/components/ui/prose";
import { DataFooter } from "@/components/ui/data-footer";
import { getKits } from "@/lib/get-kits";
import { getKitsUpdated } from "@/lib/data-meta";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Editorial Policy: How Rankings Are Generated",
  description:
    "OffGridEmpire rankings are threshold-driven from retailer data. No editor's pick, no sponsor influence, no subjective rewrites. Here is the policy.",
  alternates: { canonical: "/editorial-policy" },
  openGraph: {
    title: "Editorial Policy: How Rankings Are Generated",
    description:
      "Threshold-driven rankings, correction process, and conflict rules.",
    url: "/editorial-policy",
  },
};

export default function EditorialPolicyPage() {
  const kitCount = getKits().length;
  const updated = getKitsUpdated();

  return (
    <ProseContainer>
      <BreadcrumbJsonLd
        items={[
          { name: "Home", url: "/" },
          { name: "Editorial Policy", url: "/editorial-policy" },
        ]}
      />

      <Breadcrumb
        items={[{ href: "/", label: "Home" }, { label: "Editorial Policy" }]}
      />

      <PageTitle title="Editorial Policy" />

      <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4 max-w-prose">
        OffGridEmpire is a data tool, not a buyer&apos;s guide. Every ranking,
        verdict, and callout on the site is generated from thresholds applied
        to the same dataset. No kit is ever elevated, buried, or rewritten
        because of sponsor relationships. This page documents how that works
        and what to do if you believe something is wrong.
      </p>

      <DataFooter kitCount={kitCount} updated={updated} />

      <ContentCard>
        <SectionHeading id="principles">Core Principles</SectionHeading>
        <ul className="list-disc list-inside text-sm text-[var(--text-secondary)] space-y-2 mb-4 ml-2">
          <li>
            <strong className="text-[var(--text-primary)]">No editor&apos;s pick.</strong> Rankings are threshold-driven from real build cost, completeness, cost-per-watt, and cohort percentile. If two kits tie on the underlying metric, they tie on the page.
          </li>
          <li>
            <strong className="text-[var(--text-primary)]">No sponsor influence.</strong> Affiliate partnerships pay the same commission regardless of ranking. A kit will never move because of a retailer relationship.
          </li>
          <li>
            <strong className="text-[var(--text-primary)]">No hidden rewrites.</strong> Product descriptions come from retailer data feeds, lightly normalized for formatting. The site never invents specs.
          </li>
          <li>
            <strong className="text-[var(--text-primary)]">Cohort-based comparisons.</strong> A 2,000W kit is compared against other 2,000W kits, not against the whole dataset. Percentile labels (&quot;best value&quot;, &quot;most overpriced&quot;) are calculated against the relevant cohort.
          </li>
        </ul>

        <SectionHeading id="how-rankings-work">How Rankings Are Generated</SectionHeading>
        <Paragraph>
          Every listing page — category, brand, use-case, budget, hub — pulls
          from the same{" "}
          <Link
            href="/data-sources"
            className="text-[var(--accent)] hover:underline"
          >
            retailer dataset
          </Link>
          . Kits are filtered by the page&apos;s scope, then ranked on a
          single metric (real build cost, cost per watt-hour, completeness,
          or use-case score). The ranking function is deterministic: same
          dataset, same order.
        </Paragraph>
        <Paragraph>
          Verdict labels like &quot;best true value&quot; or &quot;sticker-price
          trap&quot; are generated by threshold rules, not written by hand. A kit
          carries the label only if the numbers qualify it on that page&apos;s
          cohort.
        </Paragraph>

        <SectionHeading id="conflicts">Conflict Rules</SectionHeading>
        <Paragraph>
          OffGridEmpire earns affiliate commissions from most retailers in the
          dataset. These relationships do not change rankings, labels, or
          verdicts. Specifically:
        </Paragraph>
        <ul className="list-disc list-inside text-sm text-[var(--text-secondary)] space-y-1 mb-4 ml-2">
          <li>No retailer sees the ranking logic before it ships.</li>
          <li>No retailer can request removal of a negative label for a kit that qualifies for it.</li>
          <li>No kit is excluded from the dataset because of commission rate.</li>
          <li>Affiliate disclosures appear sitewide; details live on the <Link href="/affiliate-disclosure" className="text-[var(--accent)] hover:underline">disclosure page</Link>.</li>
        </ul>

        <SectionHeading id="update-policy">Update Policy</SectionHeading>
        <Paragraph>
          Prices and stock status refresh every 6–12 hours. Kit metadata
          (included components, voltage, chemistry) is re-evaluated whenever
          the source feed changes the underlying spec. When a kit is delisted
          or its price becomes unrecoverable, the page is kept live but shows
          a &quot;no current listing&quot; notice and drops out of ranked tables.
        </Paragraph>

        <SectionHeading id="corrections">Corrections</SectionHeading>
        <Paragraph>
          Any user can request a correction via{" "}
          <Link href="/contact" className="text-[var(--accent)] hover:underline">
            contact
          </Link>
          . Corrections are investigated against the retailer feed. If a number
          is wrong, it is fixed and the next data export republishes
          everywhere the number appeared. We do not keep an ad-hoc override
          layer; a correction either lives in the data or it does not appear.
        </Paragraph>

        <SectionHeading id="scope">What This Policy Does Not Cover</SectionHeading>
        <ul className="list-disc list-inside text-sm text-[var(--text-secondary)] space-y-1 mb-4 ml-2">
          <li>Retailer pricing decisions — we report, we do not set, retail prices.</li>
          <li>Product quality claims beyond what the spec sheet supports.</li>
          <li>Installation advice, warranty arbitration, or product returns.</li>
        </ul>

        <Paragraph>
          For questions about specific numbers, start with{" "}
          <Link
            href="/how-real-build-cost-is-calculated"
            className="text-[var(--accent)] hover:underline"
          >
            how real build cost is calculated
          </Link>{" "}
          and{" "}
          <Link
            href="/methodology"
            className="text-[var(--accent)] hover:underline"
          >
            full methodology
          </Link>
          .
        </Paragraph>
      </ContentCard>

      <div className="mt-8 flex flex-wrap gap-3 justify-center">
        <Link
          href="/methodology"
          className="inline-flex items-center gap-2 rounded border border-[var(--border)] bg-[var(--bg-surface)] px-5 py-2.5 text-sm font-medium text-[var(--text-secondary)] hover:border-[var(--border-accent)] hover:text-[var(--accent)] transition-colors"
        >
          Full methodology
        </Link>
        <Link
          href="/data-sources"
          className="inline-flex items-center gap-2 rounded border border-[var(--border)] bg-[var(--bg-surface)] px-5 py-2.5 text-sm font-medium text-[var(--text-secondary)] hover:border-[var(--border-accent)] hover:text-[var(--accent)] transition-colors"
        >
          Data sources
        </Link>
      </div>
    </ProseContainer>
  );
}
